// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'example_component': string;
}
export const cssExports: CssExports;
export default cssExports;
