// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'component': string;
  'interactionLayer': string;
  'stage': string;
}
export const cssExports: CssExports;
export default cssExports;
